#example 1
stages:
- name: Build and Publish my image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: happyit/app:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
- name: Deploy some workloads
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml

# branch conditions for the pipeline
branch:
  include: [ master, feature/*]
  exclude: [ dev ]

# timeout in minutes
timeout: 30